const demoText = `Чтение — это не гонка. Когда взгляд перестаёт перескакивать между строками, мозг получает больше пространства для смысла. RSVP помогает убрать лишние движения глаз и спокойно удерживать внимание на одном слове за раз. Начни с комфортной скорости, а затем постепенно добавляй темп. Хорошая скорость — та, на которой ты понимаешь текст и хочешь читать дальше.`;
const $ = (id) => document.getElementById(id);
const state = { words: [], index: Number(localStorage.getItem('tempo-position')) || 0, speed: Number(localStorage.getItem('tempo-speed')) || 320, playing: false, timer: null, smart: localStorage.getItem('tempo-smart') !== 'false', orp: localStorage.getItem('tempo-orp') !== 'false', onboarding: localStorage.getItem('tempo-onboarded') === 'true' };
const ui = { text: $('textInput'), wordCount: $('wordCount'), word: $('wordDisplay'), speed: $('speedInput'), speedValue: $('speedValue'), progress: $('progressBar'), position: $('positionLabel'), time: $('timeLeft'), status: $('statusLabel'), play: $('playButton'), smart: $('smartPauses'), orp: $('orpToggle') };
function parseText(){ state.words = ui.text.value.trim().split(/\s+/).filter(Boolean); if(state.index >= state.words.length) state.index = Math.max(0,state.words.length-1); localStorage.setItem('tempo-text', ui.text.value); ui.wordCount.textContent = `${state.words.length} слов`; render(); }
function orpWord(word){ if(!state.orp) return word; const clean = word.replace(/[^\p{L}\p{N}]/gu,''); if(!clean) return word; const pivot = Math.floor((clean.length-1)*0.43); let seen=0; return [...word].map(ch=>{ if(/[\p{L}\p{N}]/u.test(ch)){ const out = seen===pivot ? `<span class="orp">${ch}</span>` : ch; seen++; return out } return ch }).join(''); }
function render(){ const current=state.words[state.index] || ''; ui.word.innerHTML=current ? orpWord(current) : '<span class="placeholder-word">твой<br/>фокус</span>'; const total=state.words.length; const done=total ? (state.index+1)/total*100 : 0; ui.progress.style.width=`${done}%`; ui.position.textContent=`${total ? state.index+1 : 0} / ${total}`; const seconds=total ? Math.max(0,(total-state.index-1)*60/state.speed) : 0; ui.time.textContent=total ? formatTime(seconds) : '—'; ui.status.textContent=state.playing ? 'Читаем' : (state.index ? 'На паузе' : 'Готов к чтению'); ui.play.textContent=state.playing ? 'Ⅱ' : '▶'; localStorage.setItem('tempo-position', state.index); }
function formatTime(sec){ const m=Math.floor(sec/60), s=Math.round(sec%60); return m ? `ещё ${m} мин ${String(s).padStart(2,'0')} сек` : `ещё ${s} сек`; }
function delay(){ let ms=60000/state.speed; const word=state.words[state.index]||''; if(state.smart){ if(/[.!?…]$/.test(word)) ms*=1.8; else if(/[,;:]$/.test(word)) ms*=1.35; if(word.replace(/[^\p{L}]/gu,'').length>9) ms*=1.2; } return ms; }
function tick(){ if(!state.playing) return; if(state.index >= state.words.length-1){ state.playing=false; render(); return } state.index++; render(); state.timer=setTimeout(tick,delay()); }
function togglePlay(){ if(ui.text.value !== localStorage.getItem('tempo-text')) handleTextChange(); if(!state.words.length){ ui.text.focus(); return } state.playing=!state.playing; clearTimeout(state.timer); render(); if(state.playing) state.timer=setTimeout(tick,delay()); }
function move(delta){ state.playing=false; clearTimeout(state.timer); state.index=Math.max(0,Math.min(Math.max(0,state.words.length-1),state.index+delta)); render(); }
async function toggleFullscreen(){ const reader=$('readerCard'); const active=Boolean(document.fullscreenElement)||document.body.classList.contains('fullscreen-active'); if(!active){ await reader.requestFullscreen?.(); } else { await document.exitFullscreen?.(); document.body.classList.remove('fullscreen-active'); syncFullscreenButton(); } }
function syncFullscreenButton(){ const active=Boolean(document.fullscreenElement); $('fullscreenButton').textContent=active?'×':'⛶'; $('fullscreenButton').title=active?'Выйти из полноэкранного режима':'На весь экран'; $('fullscreenButton').setAttribute('aria-label', $('fullscreenButton').title); document.body.classList.toggle('fullscreen-active',active); }
function handleTextChange(){ state.index=0; state.playing=false; clearTimeout(state.timer); parseText(); }
ui.text.addEventListener('input',handleTextChange); ui.speed.value=state.speed; ui.speedValue.textContent=state.speed; ui.smart.checked=state.smart; ui.orp.checked=state.orp; ui.speed.addEventListener('input',e=>{state.speed=Number(e.target.value);ui.speedValue.textContent=state.speed;localStorage.setItem('tempo-speed',state.speed);render()}); ui.smart.addEventListener('change',e=>{state.smart=e.target.checked;localStorage.setItem('tempo-smart',state.smart)}); ui.orp.addEventListener('change',e=>{state.orp=e.target.checked;localStorage.setItem('tempo-orp',state.orp);render()}); $('playButton').addEventListener('click',togglePlay); $('backButton').addEventListener('click',()=>move(-1)); $('forwardButton').addEventListener('click',()=>move(1)); $('restartButton').addEventListener('click',()=>{state.index=0;state.playing=false;clearTimeout(state.timer);render()}); $('loadDemo').addEventListener('click',()=>{ui.text.value=demoText;state.index=0;parseText()}); $('resetButton').addEventListener('click',()=>{ui.text.value='';state.index=0;state.playing=false;clearTimeout(state.timer);parseText();ui.text.focus()}); $('startOnboarding').addEventListener('click',()=>{localStorage.setItem('tempo-onboarded','true');$('onboarding').style.display='none';document.body.classList.add('reading');ui.text.focus()}); $('langToggle').addEventListener('click',()=>{alert('EN-ready: language strings are centralized for the next iteration.')}); $('fullscreenButton').addEventListener('click',toggleFullscreen); document.addEventListener('fullscreenchange',syncFullscreenButton); ui.text.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();togglePlay()}}); $('readerStage').addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();togglePlay()} if(e.code==='ArrowLeft')move(-1);if(e.code==='ArrowRight')move(1)}); if(state.onboarding){$('onboarding').style.display='none';document.body.classList.add('reading')} ui.text.value=localStorage.getItem('tempo-text') || ''; parseText();
